export const transactionData = [
  'Transaction Date Time',
  'Transaction ID',
  'Transaction Type',
  'Line ID',
  'Station ID',
  'Equipment Group ID',
  'Equipment ID',
  'Acquirer ID',
  'Operator ID',
  'Terminal ID',
  'Pan Sha',
  'Service Type',
  'Tom Efo Shift ID',
  'Paytm TID',
  'Paytm MID',
  'Business Date',
  'Status',
];
export const cardMasterData = [
  'Customer Name',
  'Customer Mobile Number',
  'Transaction ID',
  'Transaction Type',
  'Line ID',
  'Station ID',
  'Equipment Group ID',
  'Equipment ID',
  'Acquirer ID',
  'Operator ID',
  'Terminal ID',
  'Card Type',
  'Pan Sha',
  'Product Type',
  'Business Date',
  'Transaction Date Time',
];

export const exportStationsData = [
  'Station Name',
  'Short Name',
  'Line',
  'IP Address SC',
  'IP Address CC',
  'Status',
];

export const exportLinesData = [
  'Line Id',
  'Line Name',
  'Line Short Name',
  'Status',
];

export const exportUsersData = [
  'User code',
  'Name',
  'Role',
  'Station',
  'Line',
  'Status',
];
export const exportRolesData = [
  'Role Code',
  'Role Name',
  'Role Privileges',
  'Status',
];
export const exportPriviledgesData = [
  'Privilege Code',
  'Privilege Type',
  'Status',
];

export const exportOverStayConfigurationData = [
  'Same Station Exit',
  'Over Stay Duration From',
  'Over Stay Duration To',
  'Penalty Amount',
];

export const exportAdjustmentsData = [
  'Param Id',
  'Adjustment Code',
  'Adjustment Name',
  'Adjustment Amount',
  'Parameter Version',
  'Status',
];
export const exportSurcharge = [
  'Param Id',
  'Surcharge Code',
  'Surcharge Name',
  'Surcharge Amount',
  'Parameter Version',
  'Status',
];
export const shiftstartTableData = [
  'Shift Start Date Time',
  'Line Id',
  'Station Id',
  'Equipment Group Id',
  'Equepment Id',
  'Acquirer Id',
  'Operator Id',
  'Terminal Id',
  'Agent Id',
  'Tom Efo Shift Start',
];
export const shiftEndReportData = [
  'Id',
  'Equipment ID',
  'Acquirer ID',
  'Opertator ID',
  'Terminal ID',
  'Agent ID',
  'Shift ID',
  'Business Date',
  'Shift Start Time',
  'Shift End Time',
];
export const entrySummaryReportData = [
  'Transaction Date',
  'Station Name',
  'Equipment Group Id',
  'Equipment Id',
  'Card Type',
  'Count',
];
export const exitSummaryReportData = [
  'Transaction Date',
  'Station Name',
  'Equipment Group Id',
  'Equipment Id',
  'Card Type',
  'Count',
];
export const ridershipTableData = [
  'Station Id',
  'Station Name',
  'Entry Count',
  'Exit Count',
];

export const reconsillationTableData = [
  'Afc Transaction Type',
  'Afc Payment Method',
  'Recon Status',
  'Transaction Date',
  'Transaction Id',
  'Ppbl Transaction Type',
  'Ppbl Payment Method',
  'Merchant Name',
  'Order Id',
  'Issuing Bank',
  'Payment Amount',
  'Detail No',
  'Merchant Id',
  'Original Merchant Id',
  'Mbid',
  'Payment Type',
  'Payment Currency',
  'Response Code',
  'Bank Txn Id',
  'User Cust Id',
  'Bank Gate Way',
  'Status',
  'Bank Fee Currency',
  'Bank Fee Amount',
  'Merchant Commission',
  'Service Tax',
  'Convenience Fee',
  'Convenience Tax',
  'Settled Date',
  'Refund Amount',
  'Industry',
  'Settlement Txn Id',
  'Inst Code',
  'External Serial No',
  'Recon Id',
  'Settlement Type',
  'Settle Type',
  'Split Flag',
  'Voucher code',
  'Aggregator Merchant Id',
  'Prepa Id Card',
  'Product Code',
  'Card Network',
  'Instant Settlement',
  'Pwp Category',
  'Fee Factor',
  'Acquiring Fee',
  'Platform Fee',
  'Acquiring Tax',
  'Platform Tax',
  'Add Money Type',
  'Corporate Card',
  'Utr',
  'First Six Digits',
  'Last Four Digits',
  'Payer Masked Card No',
  'Masked Token No',
  'Dcc Id',
  'Merchant Solution Type',
  'Split Field Dl Last Updated',
  'Bank Tid',
  'Appr Code',
  'Sub Wallet Fee Details',
  'SubWallet Tax Details',
  'Convenience Plat Form Fee',
  'Convenience Platform Fee Service Tax',
  'Order Success Time',
  'Stan',
  'Run Type',
  'Run Date',
  'Split Type',
  'Split Delay',
  'Upi Mode Sub Type',
  'Dl Last Updated',
  'Insert Time',
];
export const transactionsequenceTableData = [
  'Station Id',
  'Equipment Id',
  'Transaction Type',
  'Transaction Sequence Number',
  'Status',
  'Business Date',
];
