export const transactionData = [
  'Transaction Date Time',
  'Transaction ID',
  'Transaction Type',
  'Line ID',
  'Station ID',
  'Equipment Group ID',
  'Equipment ID',
  'Acquirer ID',
  'Operator ID',
  'Terminal ID',
  'Pan Sha',
  'Service Type',
  'Tom Efo Shift ID',
  'Paytm TID',
  'Paytm MID',
  'Business Date',
  'Status',
];
export const cardMasterData = [
  'Customer Name',
  'Customer Mobile Number',
  'Transaction ID',
  'Transaction Type',
  'Line ID',
  'Station ID',
  'Equipment Group ID',
  'Equipment ID',
  'Acquirer ID',
  'Operator ID',
  'Terminal ID',
  'Card Type',
  'Pan Sha',
  'Product Type',
  'Business Date',
  'Transaction Date Time',
];

export const exportStationsData = [
  'Station Name',
  'Short Name',
  'Line',
  'IP Address SC',
  'IP Address CC',
  'Status',
];

export const exportLinesData = [
  'Line Id',
  'Line Name',
  'Line Short Name',
  'Status',
];

export const exportUsersData = [
  'User code',
  'Name',
  'Role',
  'Station',
  'Line',
  'Status',
];
export const exportRolesData = [
  'Role Code',
  'Role Name',
  'Role Privileges',
  'Status',
];
export const exportPriviledgesData = [
  'Privilege Code',
  'Privilege Type',
  'Status',
];
export const shiftstartTableData = [
  'shift_start_date_time',
  'lineId',
  'stationId',
  'equipmentGroupId',
  'equepmentId',
  'acquirerId',
  'operatorId',
  'terminalId',
  'agentId',
  'tom_Efo_Shift_start',
];
export const shiftEndReportData = [
  'id',
  'equipmentID',
  'acquirerID',
  'opertatorID',
  'terminalID',
  'agentID',
  'shiftID',
  'businessDate',
  'shiftStartTime',
  'shiftEndTime',
];
export const entrySummaryReportData = [
  'transactionDate',
  'stationName',
  'equipmentGroupId',
  'equipmentId',
  'cardType',
  'count',
];
export const exitSummaryReportData = [
  'transactionDate',
  'stationName',
  'equipmentGroupId',
  'equipmentId',
  'cardType',
  'count',
];
export const ridershipTableData = [
  'stationId',
  'stationName',
  'entryCount',
  'exitCount',
];

export const reconsillationTableData = [
  'afcTransactionType',
  'afcPaymentMethod',
  'reconStatus',
  'transactionDate',
  'transactionId',
  'ppblTransactionType',
  'ppblPaymentMethod',
  'merchantName',
  'orderId',
  'issuingBank',
  'paymentAmount',
  'detailNo',
  'merchantId',
  'originalMerchantId',
  'mbid',
  'paymentType',
  'paymentCurrency',
  'responseCode',
  'bankTxnId',
  'userCustId',
  'bankGateWay',
  'status',
  'bankFeeCurrency',
  'bankFeeAmount',
  'merchantCommission',
  'serviceTax',
  'convenienceFee',
  'convenienceTax',
  'settledDate',
  'refundAmount',
  'industry',
  'settlementTxnId',
  'instCode',
  'externalSerialNo',
  'reconId',
  'settlementType',
  'settleType',
  'splitFlag',
  'vouchercode',
  'aggregatorMerchantId',
  'prepaidCard',
  'productCode',
  'cardNetwork',
  'instantSettlement',
  'pwpCategory',
  'feeFactor',
  'acquiringFee',
  'platformFee',
  'acquiringTax',
  'platformTax',
  'addMoneyType',
  'corporateCard',
  'utr',
  'firstSixDigits',
  'lastFourDigits',
  'payerMaskedCardNo',
  'maskedTokenNo',
  'dccId',
  'merchantSolutionType',
  'splitFieldDlLastUpdated',
  'bankTid',
  'apprCode',
  'subWalletFeeDetails',
  'subWalletTaxDetails',
  'conveniencePlatformFee',
  'conveniencePlatformFeeServiceTax',
  'orderSuccessTime',
  'stan',
  'runType',
  'runDate',
  'splitType',
  'splitDelay',
  'upiModeSubType',
  'dlLastUpdated',
  'insertTime',
];
export const transactionsequenceTableData = [
  'stationId',
  'equipmentId',
  'transactionType',
  'transactionsequenceNumber',
  'status',
  'businessDate',
];
