export const transactionQueryData = {
  headers: [
    { key: 'transactionDateTime', label: 'Transaction Date Time' },
    { key: 'transId', label: 'Transaction ID' },
    { key: 'transType', label: 'Transaction Type' },
    { key: 'lineId', label: 'Line ID' },
    { key: 'stationId', label: 'Station ID' },
    { key: 'equipmentGroupId', label: 'Equipment Group ID' },
    { key: 'equipId', label: 'Equipment ID' },
    { key: 'acquirerId', label: 'Acquirer ID' },
    { key: 'operatorId', label: 'Operator ID' },
    { key: 'terminalId', label: 'Terminal ID' },
    { key: 'panSha', label: 'Pan Sha' },
    { key: 'serviceType', label: 'Service Type' },
    { key: 'tomEfoShiftId', label: 'Tom Efo Shift ID' },
    { key: 'paytmTid', label: 'Paytm TID' },
    { key: 'paytmMid', label: 'Paytm MID' },
    { key: 'bussinessDate', label: 'Business Date' },
    { key: 'status', label: 'Status' },
  ],
  data: [
    {
      transactionDateTime: '03-Feb-2611 06:50:25',
      transId: '764566834220230824025339',
      transType: '03',
      lineId: '0303-Stadium',
      stationId: '3',
      equipmentGroupId: '1143',
      equipId: '4',
      acquirerId: '6014',
      operatorId: '3030C2',
      terminalId: '3030C2',
      panSha: '••••••••••••1788',
      serviceType: '1',
      tomEfoShiftId: '0303354555',
      paytmTid: '11075316',
      paytmMid: 'LTMetr33790038971459',
      bussinessDate: '24-Aug-2023',
      status: 'Active',
    },
    {
      transactionDateTime: '03-Feb-2611 06:50:25',
      transId: '764566834220230824025349',
      transType: '04',
      lineId: '0303-Stadium',
      stationId: '3',
      equipmentGroupId: '1145',
      equipId: '2',
      acquirerId: '6013',
      operatorId: '3030C2',
      terminalId: '3030C2',
      panSha: '••••••••••••1788',
      serviceType: '1',
      tomEfoShiftId: '0303354556',
      paytmTid: '11075316',
      paytmMid: 'LTMetr33790038971459',
      bussinessDate: '23-Aug-2023',
      status: 'In-Active',
    },
  ],
};

export const cardmasterData = {
  headers: [
    { key: 'customerName', label: 'Customer Name' },
    { key: 'customerMobileNo', label: 'Customer Mobile Number' },
    { key: 'trxId', label: 'Transaction ID' },
    { key: 'trxType', label: 'Transaction Type' },
    { key: 'lineId', label: 'Line ID' },
    { key: 'stationId', label: 'Station ID' },
    { key: 'equpGrpId', label: 'Equipment Group ID' },
    { key: 'equpId', label: 'Equipment ID' },
    { key: 'aqurId', label: 'Acquirer ID' },
    { key: 'operId', label: 'Operator ID' },
    { key: 'trmId', label: 'Terminal ID' },
    { key: 'crdType', label: 'Card Type' },
    { key: 'panSha', label: 'Pan Sha' },
    { key: 'prdType', label: 'Product Type' },
    { key: 'businessDt', label: 'Business Date' },
    { key: 'trxDtTm', label: 'Transaction Date Time' },
  ],
  data: [
    {
      customerName: 'John Doe',
      customerMobileNo: '1234567890',
      trxId: 'ABC123',
      trxType: 'Purchase',
      lineId: 'Line ',
      stationId: 'Station ',
      equpGrpId: 'Group ',
      equpId: 'Equipment ',
      aqurId: 'Acquirer ',
      operId: 'Operator ',
      trmId: 'Terminal ',
      crdType: 'Credit',
      panSha: 'XXXX-XXXX-XXXX-234',
      prdType: 'Product ',
      businessDt: '2024-04-15',
      trxDtTm: '2024-04-15T10:30:00',
    },
    {
      customerName: 'Jane Smith',
      customerMobileNo: '9876543210',
      trxId: 'XYZ789',
      trxType: 'Refund',
      lineId: 'Line ',
      stationId: 'Station ',
      equpGrpId: 'Group ',
      equpId: 'Equipment ',
      aqurId: 'Acquirer ',
      operId: 'Operator ',
      trmId: 'Terminal ',
      crdType: 'Debit',
      panSha: 'XXXX-XXXX-XXXX-5678',
      prdType: 'Product ',
      businessDt: '2024-04-16',
      trxDtTm: '2024-04-16T14:45:00',
    },
  ],
};

export const stationsData = {
  headers: [
    { key: 'stationName', label: 'Station Name' },
    { key: 'shortname', label: 'Short Name' },
    { key: 'line', label: 'Line' },
    { key: 'ipAddSc', label: 'IP Address SC' },
    { key: 'ipAddCC', label: 'IP Address CC' },
    { key: 'status', label: 'Status' },
  ],
  data: [
    {
      stationId: 32,
      stationName: 'Meenambakkam Metro',
      shortname: 'MNB Metro',
      line: 'CORRIDOR-I',
      ipAddSc: '10.1.2.0',
      ipAddCC: '10.1.2.0',
      status: 'Active',
    },
    {
      stationId: 35,
      stationName: 'Alandur',
      shortname: 'Ald',
      line: 'CORRIDOR-II',
      ipAddSc: '10.1.9.0',
      ipAddCC: '10.1.8.0',
      status: 'In-Active',
    },
  ],
};

export const linesData = {
  headers: [
    { key: 'lineId', label: 'Line Id' },
    { key: 'lineName', label: 'Line Name' },
    { key: 'lineShortname', label: 'Line Short Name' },
    { key: 'status', label: 'Status' },
  ],
  data: [
    {
      lineId: 1,
      lineName: 1101,
      lineShortname: 5,
      status: 'Active',
    },
    {
      lineId: 2,
      lineName: 1100,
      lineShortname: 5,
      status: 'In-Active',
    },
  ],
};

export const usersData = {
  headers: [
    { key: 'userCode', label: 'User code' },
    { key: 'name', label: 'Name' },
    { key: 'role', label: 'Role' },
    { key: 'station', label: 'Station' },
    { key: 'line', label: 'Line' },
    { key: 'status', label: 'Status' },
  ],
  data: [
    {
      userCode: 11,
      name: 'Rajesh',
      role: 'Admin',
      station: 'Meenambakkam Metro',
      line: 'Carridor-I',
      status: 'In-Active',
    },
  ],
};

export const roleData = {
  headers: [
    { key: 'roleCode', label: 'Role code' },
    { key: 'roleName', label: 'Role Name' },
    { key: 'rolePrivileges', label: 'Role Privileges' },
    { key: 'status', label: 'Status' },
  ],
  data: [
    {
      roleCode: 111,
      roleName: 'Reports',
      rolePrivileges: 'Exit Summary Report',
      status: 'Active',
    },
  ],
};

export const privilegesData = {
  headers: [
    { key: 'privilegeCode', label: 'Privilege Code' },
    { key: 'privilegeType', label: 'Privilege Type' },
    { key: 'status', label: 'Status' },
  ],
  data: [
    {
      privilegeCode: 111,
      privilegeType: 'Monitoring',
      status: 'Active',
    },
  ],
};



export const shiftenddata = {
  headers: [
    { key: 'id', label: 'Id' },
    { key: 'equipmentID', label: 'Equipment Id' },
    { key: 'acquirerID', label: 'Acquiree Id' },
    { key: 'opertatorID', label: 'Operatator Id' },
    { key: 'terminalID', label: 'Terminal Id' },
    { key: 'agentID', label: 'Agent Id' },
    { key: 'shiftID', label: 'Shift Id' },
    { key: 'businessDate', label: 'Business Date' },
    { key: 'shiftStartTime', label: 'Shift Start Time' },
    { key: 'shiftEndTime', label: 'Shift End Time' },
  ],
  data: [
    {
      id: '1',
      equipmentID: '1006',
      acquirerID: '2',
      opertatorID: '6012',
      terminalID: '101C6',
      agentID: '1106',
      shiftID: '101370918',
      businessDate: '29-Feb-2023',
      shiftStartTime: '30-Dec-2023 09:35:29',
      shiftEndTime: '30-Dec-2023 09:35:29',
    },
    {
      id: '2',
      equipmentID: 1005,
      acquirerID: 4,
      opertatorID: 6014,
      terminalID: '101C3',
      agentID: 1105,
      shiftID: 101370919,
      businessDate: '30-Mar-2024',
      shiftStartTime: '30-Oct-2023 12:35:29',
      shiftEndTime: '12-Oct-2023 12:35:29',
    },
  ],
};

export const entrysummarydata = {
  headers: [
    { key: 'transactionDate', label: 'Transaction Date' },
    { key: 'stationName', label: 'Station Name' },
    { key: 'equipmentGroupId', label: 'Equipment Group Id' },
    { key: 'equipmentId', label: 'Equipment Id' },
    { key: 'cardType', label: 'Card Type' },
    { key: 'count', label: 'Count' },
  ],
  data: [
    {
      transactionDate: '13 feb 2024',
      stationName: '0101 miyapur',
      equipmentGroupId: 4,
      equipmentId: 4002,
      cardType: 1,
      count: 2,
    },

    {
      transactionDate: '13 feb 2024',
      stationName: '0102 nagole',
      equipmentGroupId: 4,
      equipmentId: 4002,
      cardType: 2,
      count: 2,
    },
  ],
};

export const exitsummarydata = {
  headers: [
    { key: 'transactionDate', label: 'Transaction Date' },
    { key: 'stationName', label: 'Station Name' },
    { key: 'equipmentGroupId', label: 'Equipment Group Id' },
    { key: 'equipmentId', label: 'Equipment Id' },
    { key: 'cardType', label: 'Card Type' },
    { key: 'count', label: 'Count' },
  ],
  data: [
    {
      transactionDate: '13 feb 2024',
      stationName: '0101 miyapur',
      equipmentGroupId: 4,
      equipmentId: 4002,
      cardType: 1,
      count: 2,
    },

    {
      transactionDate: '13 feb 2024',
      stationName: '0102 nagole',
      equipmentGroupId: 4,
      equipmentId: 4002,
      cardType: 2,
      count: 2,
    },
  ],
};

export const ridershipdata = {
  headers: [
    { key: 'stationId', label: 'Station Id' },
    { key: 'stationName', label: 'Station Name' },
    { key: 'entryCount', label: 'Entry Count' },
    { key: 'exitCount', label: 'Exit Count' },
  ],
  data: [
    {
      stationId: '0101',
      stationName: 'miyapur',
      entryCount: 0,
      exitCount: 0,
    },
  ],
};

export const reconsillationData = {
  headers: [
    { key: 'afcTransactionType', label: 'Afc Transaction Type' },
    { key: 'afcPaymentMethod', label: 'Afc Payment Method' },
    { key: 'reconStatus', label: 'Recon Status' },
    { key: 'transactionDate', label: 'Transaction Date' },
    { key: 'transactionId', label: 'Transaction Id' },
    { key: 'ppblTransactionType', label: 'PPBL Transaction Type' },
    { key: 'ppblPaymentMethod', label: 'PPBL Payment Method' },
    { key: 'merchantName', label: 'Merchant Name' },
    { key: 'orderId', label: 'Order Id' },
    { key: 'issuingBank', label: 'Issuing Bank' },
    { key: 'paymentAmount', label: 'Payment Amount' },
    { key: 'detailNo', label: 'Detail No' },
    { key: 'merchantId', label: 'Merchant Id' },
    { key: 'originalMerchantId', label: 'Original Merchant' },
    { key: 'mbid', label: 'Mbid' },
    { key: 'paymentType', label: 'Payment Type' },
    { key: 'paymentCurrency', label: 'Payment Currency' },
    { key: 'responseCode', label: 'Response Code' },
    { key: 'bankTxnId', label: 'Bank Txn Id' },
    { key: 'userCustId', label: 'User Cust Id' },
    { key: 'bankGateWay', label: 'Bank Gate Way' },
    { key: 'status', label: 'Status' },
    { key: 'bankFeeCurrency', label: 'Bank Fee Currency' },
    { key: 'bankFeeAmount', label: 'Bank Fee Amount' },
    { key: 'merchantCommission', label: 'Merchant Commission' },
    { key: 'serviceTax', label: 'Service Tax' },
    { key: 'convenienceFee', label: 'Convenience Fee' },
    { key: 'convenienceTax', label: 'Convenience Tax' },
    { key: 'settledDate', label: 'Settle Date' },
    { key: 'refundAmount', label: 'Refund Amount' },
    { key: 'industry', label: 'Industry' },
    { key: 'settlementTxnId', label: 'Settlement Txn Id' },
    { key: 'instCode', label: 'Inst Code' },
    { key: 'externalSerialNo', label: 'External Serial No' },
    { key: 'reconId', label: 'Recon Id' },
    { key: 'settlementType', label: 'Settlement Type' },
    { key: 'settleType', label: 'Settle Type' },
    { key: 'splitFlag', label: 'Split Flag' },
    { key: 'vouchercode', label: 'VoucherCode' },
    { key: 'aggregatorMerchantId', label: 'Aggregator Merchant Id' },
    { key: 'prepaidCard', label: 'Prepa Id Card' },
    { key: 'productCode', label: 'Product Code' },
    { key: 'cardNetwork', label: 'Card Network' },
    { key: 'instantSettlement', label: 'Instant Settlement' },
    { key: 'pwpCategory', label: 'Pwp Category' },
    { key: 'feeFactor', label: 'Fee Factor' },
    { key: 'acquiringFee', label: 'Acquiring Fee' },
    { key: 'platformFee', label: 'PlatformFee' },
    { key: 'acquiringTax', label: 'Acquiring Tax' },
    { key: 'platformTax', label: 'Platform Tax' },
    { key: 'addMoneyType', label: 'AddMoney Type' },
    { key: 'corporateCard', label: 'Corporate Card' },
    { key: 'utr', label: 'Utr' },
    { key: 'firstSixDigits', label: 'First Six Digits' },
    { key: 'lastFourDigits', label: 'Last Four Digits' },
    { key: 'payerMaskedCardNo', label: 'payer Masked Card No' },
    { key: 'maskedTokenNo', label: 'Masked Token No' },
    { key: 'dccId', label: 'Dcc Id' },
    { key: 'merchantSolutionType', label: 'Merchant Solution Type' },
    { key: 'splitFieldDlLastUpdated', label: 'Split FieldDl LastUpdated' },
    { key: 'bankTid', label: 'Bank Tid' },
    { key: 'apprCode', label: 'Appr Code' },
    { key: 'subWalletFeeDetails', label: 'Sub Wallet Fee Details' },
    { key: 'subWalletTaxDetails', label: 'Sub Wallet Tax Details' },
    { key: 'conveniencePlatformFee', label: 'Convenience Plat FormFee' },
    {
      key: 'conveniencePlatformFeeServiceTax',
      label: 'Convenience Plat Form Fee ServiceTax',
    },
    { key: 'orderSuccessTime', label: 'Order Success Time' },
    { key: 'stan', label: 'Stan' },
    { key: 'runType', label: 'Run Type' },
    { key: 'runDate', label: 'Run Date' },
    { key: 'splitType', label: 'Split Type' },
    { key: 'splitDelay', label: 'Split Delay' },
    { key: 'upiModeSubType', label: 'Upi Mode Sub Type' },
    { key: 'dlLastUpdated', label: 'Dl Last Updated' },
    { key: 'insertTime', label: 'Insert Time' },
  ],
  data: [
    {
      afcTransactionType: 'AFC123',
      afcPaymentMethod: 'Credit Card',
      reconStatus: 'Pending',
      transactionDate: '2024-04-19',
      transactionId: '123456789',
      ppblTransactionType: 'PPBL123',
      ppblPaymentMethod: 'PayPal',
      merchantName: 'Dummy Merchant',
      orderId: 'ORD123',
      issuingBank: 'Bank of Dummy',
      paymentAmount: '100.00',
      detailNo: '1',
      merchantId: 'M123',
      originalMerchantId: 'M456',
      mbid: 'MB123',
      paymentType: 'Online',
      paymentCurrency: 'USD',
      responseCode: '200',
      bankTxnId: 'BT123',
      userCustId: 'CUST123',
      bankGateWay: 'Gateway123',
      status: 'Success',
      bankFeeCurrency: 'USD',
      bankFeeAmount: '5.00',
      merchantCommission: '2.00',
      serviceTax: '0.50',
      convenienceFee: '1.00',
      convenienceTax: '0.25',
      settledDate: '2024-04-20',
      refundAmount: '0.00',
      industry: 'Retail',
      settlementTxnId: 'ST123',
      instCode: 'INST123',
      externalSerialNo: 'EXT123',
      reconId: 'RECON123',
      settlementType: 'Automatic',
      settleType: 'Full',
      splitFlag: 'N',
      vouchercode: 'VOUCHER123',
      aggregatorMerchantId: 'AGG123',
      prepaidCard: 'Yes',
      productCode: 'PROD123',
      cardNetwork: 'Visa',
      instantSettlement: 'Yes',
      pwpCategory: 'Category123',
      feeFactor: '1.5',
      acquiringFee: '3.00',
      platformFee: '1.50',
      acquiringTax: '0.75',
      platformTax: '0.25',
      addMoneyType: 'Online',
      corporateCard: 'No',
      utr: 'UTR123',
      firstSixDigits: '123456',
      lastFourDigits: '7890',
      payerMaskedCardNo: '************7890',
      maskedTokenNo: 'TOKEN123',
      dccId: 'DCC123',
      merchantSolutionType: 'Solution123',
      splitFieldDlLastUpdated: '2024-04-20',
      bankTid: 'TID123',
      apprCode: 'APPR123',
      subWalletFeeDetails: 'FeeDetails123',
      subWalletTaxDetails: 'TaxDetails123',
      conveniencePlatformFee: '1.00',
      conveniencePlatformFeeServiceTax: '0.25',
      orderSuccessTime: '2024-04-20',
      stan: 'STAN123',
      runType: 'Type123',
      runDate: '2024-04-20',
      splitType: 'Type123',
      splitDelay: 'No',
      upiModeSubType: 'SubType123',
      dlLastUpdated: '2024-04-20',
      insertTime: '2024-04-20',
    },
  ],
};

export const transactionsequencedata = {
  headers: [
    { key: 'stationId', label: 'Station Id' },
    { key: 'equipmentId', label: 'Equipment Id' },
    { key: 'transactionType', label: 'Transaction Type' },
    { key: 'transactionsequenceNumber', label: 'Transactionsequence Number' },
    { key: 'status', label: 'Status' },
    { key: 'businessDate', label: 'Business Date' },
  ],
  data: [
    {
      stationId: '1010',
      equipmentId: '11',
      transactionType: 22,
      transactionsequenceNumber: 33,
      status: 'yes',
      businessDate: '22-2-24',
    },
  ],
};

export const shiftstartData = {
  headers: [
    { key: 'shiftStartDateTime', label: 'Shift Start Date Time' },
    { key: 'lineId', label: 'Line Id' },
    { key: 'stationId', label: 'Station Id' },
    { key: 'equipmentGroupId', label: 'Equipment Group Id' },
    { key: 'equepmentId', label: 'Equepment Id' },
    { key: 'acquirerId', label: 'Acquirer Id' },
    { key: 'operatorId', label: 'Operator Id' },
    { key: 'terminalId', label: 'Terminal Id' },
    { key: 'agentId', label: 'Agent Id' },
    { key: 'tomEfoShiftStart', label: 'Tom Efo Shift Start' },
  ],
  data: [
    {
      shiftStartDateTime: '30-Mar-2020 10:35:29',
      lineId: '01',
      stationId: '0106-Moosapet',
      equipmentGroupId: '3',
      equepmentId: '1002',
      acquirerId: '4',
      operatorId: '6014',
      terminalId: '1010C2',
      agentId: '11102',
      tomEfoShiftStart: '0101',
    },
  ],
};

export const OverStayConfigurationData = {
  headers: [
    { key: 'sameStationExit', label: 'Same Station Exit' },
    { key: 'overStayDurationFrom', label: 'Over Stay Duration Frome' },
    { key: 'overStayDurationTo', label: 'Over Stay Duration To' },
    { key: 'penaltyAmount', label: 'Penalty Amount' },
  ],
  data: [
    {
      sameStationExit:'No',
      overStayDurationFrom: 151,
      overStayDurationTo: 211,
      penaltyAmount: 1,
    },
    {
      sameStationExit:'No',
      overStayDurationFrom: 211,
      overStayDurationTo: 270,
      penaltyAmount: 3,
    },
    {
      sameStationExit:'No',
      overStayDurationFrom: 271,
      overStayDurationTo: 330,
      penaltyAmount: 4,
    },
    {
      sameStationExit:'No',
      overStayDurationFrom: 331,
      overStayDurationTo: 999,
      penaltyAmount: 6,
    },
    {
      sameStationExit:'No',
      overStayDurationFrom: 31,
      overStayDurationTo: 90,
      penaltyAmount: 1,
    },
    {
      sameStationExit:'No',
      overStayDurationFrom: 91,
      overStayDurationTo: 150,
      penaltyAmount: 3,
    },
  ],
};